# Generated by Django 5.2 on 2026-04-16 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_pagestats_visitorsession_delete_visitorstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='trash_map', max_length=100)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor Statistic',
                'verbose_name_plural': 'Visitor Statistics',
            },
        ),
        migrations.DeleteModel(
            name='VisitorSession',
        ),
        migrations.AlterModelOptions(
            name='pagestats',
            options={'verbose_name': 'Page Statistic', 'verbose_name_plural': 'Page Statistics'},
        ),
        migrations.RemoveField(
            model_name='pagestats',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pagestats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
