# Generated by Django 5.2 on 2026-04-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_visitorstats_delete_visitorsession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagestats',
            options={},
        ),
        migrations.AddField(
            model_name='pagestats',
            name='total_seconds_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
