version: "3"  
services:
  # chrome:
  #   image: selenium/node-chrome:4.41.0
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - hub
  #   environment:
  #     HUB_HOST: hub
  #   networks:
  #     - trashit-backend 
  hub:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: "2g"
    networks:
      - trashit-backend 
  ingress:
    restart: always
    image: trashit/backend-ingress
    build: 
      context: nginx/
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - trashit-backend
    environment:
      - DOMAIN
      - DOMAINWWW
      - API_KEY
      - SECRET_KEY
      - API_URL
      - CERTIFICATE_PATH
      - PRIVATE_KEY_PATH
    volumes: 
      - static:/app/static
      - media:/app/media
      - private:/app/private
      - ssl:/etc/porkcron:ro
    depends_on:
      - porkcron
  porkcron:
    build: 
      context: porkcron/
    image: trashit/porkcron
    environment:
      - DOMAIN
      - API_KEY
      - SECRET_KEY
      - API_URL
      - CERTIFICATE_PATH
      - PRIVATE_KEY_PATH
    volumes:
      - ssl:/etc/porkcron
    depends_on:
      - backend
  getdata:
    build:
      context: trashit/
    image: trashit/backend
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        ./wait-for-it.sh db:5432 -- ./getdatastart.sh -- cron -f
    networks:
      - trashit-backend
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - ALLOWED_HOSTS
      - SITE_ID
      - WAGTAILADMIN_BASE_URL
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - CSRF_TRUSTED_ORIGINS
    volumes: 
      - static:/app/static
      - media:/app/media
      - private:/app/private
    depends_on:
      - backend
  backend:
    build:
      context: trashit/
    restart: always
    image: trashit/backend
    ports:
      - "8001:8000"
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       ./wait-for-it.sh db:5432 -- ./start.sh 
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - ALLOWED_HOSTS
      - SITE_ID
      - WAGTAILADMIN_BASE_URL
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - CSRF_TRUSTED_ORIGINS
    networks:
      - trashit-backend
    volumes: 
      - static:/app/static
      - media:/app/media
      - private:/app/private
    depends_on:
      - db 
  db:
    restart: always
    image: postgis/postgis:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - trashit-backend 
networks:
  trashit-backend:
    driver: bridge
volumes:
    static:
      driver: local
    media:
      driver: local
    private:
      driver: local
    shared:
      driver: local
    ssl:
