version: "3"  
services:
  ingress:
    restart: always
    image: trashit/backend-ingress
    build: 
      context: nginx/
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - trashit-backend
    environment:
      - DOMAIN
      - DOMAINWWW
      - API_KEY
      - SECRET_KEY
      - API_URL
      - CERTIFICATE_PATH
      - PRIVATE_KEY_PATH
    volumes: 
      - static:/app/static
      - media:/app/media
      - shared:/shared/
    depends_on:
      - porkcron
  porkcron:
    build: 
      context: porkcron/
    image: trashit/porkcron
    environment:
      - DOMAIN
      - API_KEY
      - SECRET_KEY
      - API_URL
      - CERTIFICATE_PATH
      - PRIVATE_KEY_PATH
    volumes:
      - shared:/shared/
    depends_on:
      - backend
  backend:
    restart: always
    image: trashit/backend
    ports:
      - "8001:8000"
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       ./wait-for-it.sh db:5432 -- ./start.sh 
    environment:
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - ALLOWED_HOSTS
      - SITE_ID
      - WAGTAILADMIN_BASE_URL
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - CSRF_TRUSTED_ORIGINS
    networks:
      - trashit-backend
    volumes: 
      - static:/app/static
      - media:/app/media
    depends_on:
      - db 
  db:
    restart: always
    image: postgis:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBNAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - trashit-backend 
networks:
  trashit-backend:
    driver: bridge
volumes:
    static:
      driver: local
    media:
      driver: local
    shared:
      driver: local