# Generated by Django 4.2.15 on 2024-08-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datapop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectArea',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('quarter', models.CharField(blank=True, max_length=50, null=True)),
                ('polygon_field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.polygonfield')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_type', models.CharField(blank=True, max_length=100, null=True)),
                ('the_type_en', models.CharField(blank=True, max_length=100, null=True)),
                ('the_type_fr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('the_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('packaging', models.ManyToManyField(blank=True, to='trash.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('underground', models.BooleanField(default=False)),
                ('area', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('operator', models.CharField(blank=True, max_length=1000, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('collect_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.collectarea')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.containertype')),
                ('day', models.ManyToManyField(blank=True, to='trash.weekday')),
                ('the_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype')),
            ],
        ),
        migrations.CreateModel(
            name='TrashSpecificities',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('from_local_api', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('point_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datapop.pointfield')),
                ('the_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype')),
                ('trash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.trashtype')),
            ],
        ),
        migrations.AddField(
            model_name='packaging',
            name='the_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype'),
        ),
    ]
