# Generated by Django 5.2 on 2026-04-16 13:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datapop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectArea',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_description', to='datapop.textfield')),
                ('polygon_field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.polygonfield')),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_name', to='datapop.textfield')),
            ],
        ),
        migrations.CreateModel(
            name='TheType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_type', models.CharField(blank=True, max_length=100, null=True)),
                ('the_type_en', models.CharField(blank=True, max_length=100, null=True)),
                ('the_type_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('is_osm', models.BooleanField(default=False)),
                ('icon', models.CharField(choices=[('cardboard', 'Cardboard'), ('glassbottle', 'Glass'), ('can', 'Can'), ('paper', 'Paper'), ('plasticbottle', 'Plastic'), ('recycle', 'Recycling material'), ('specialbin', 'Special waste'), ('trashicon', 'General trash'), ('shirt', 'Clothes'), ('organic', 'Organic')], default='trashicon', max_length=23)),
                ('osm_type', models.ManyToManyField(blank=True, to='trash.thetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(blank=True, max_length=1000, null=True)),
                ('the_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype')),
            ],
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('underground', models.BooleanField(default=False)),
                ('area', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('operator', models.CharField(blank=True, max_length=1000, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('collect_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.collectarea')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.containertype')),
                ('the_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype')),
                ('day', models.ManyToManyField(blank=True, to='trash.weekday')),
            ],
        ),
        migrations.CreateModel(
            name='TrashSpecificities',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('from_local_api', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('osm_trash_spec', models.ManyToManyField(blank=True, related_name='osm_trash_spec', to='datapop.pointfield')),
                ('point_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datapop.pointfield')),
                ('the_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype')),
                ('trash_type', models.ManyToManyField(blank=True, to='trash.trashtype')),
            ],
        ),
        migrations.CreateModel(
            name='TypeLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('locale', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('the_type', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_the_type', to='trash.thetype')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('the_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('packaging', models.ManyToManyField(blank=True, to='trash.packaging')),
            ],
        ),
    ]
