# Generated by Django 5.2 on 2026-05-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetype',
            name='the_type_es',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='the_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='the_type_en',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='the_type_fr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
