# Generated by Django 4.2.15 on 2024-08-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetype',
            name='foreign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_trans', to='trash.thetype'),
        ),
        migrations.AddField(
            model_name='thetype',
            name='from_local_api',
            field=models.BooleanField(default=False),
        ),
    ]
