# Generated by Django 4.2.15 on 2024-09-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_thetype_foreign_type_thetype_from_local_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='thetype',
            name='foreign_type',
        ),
        migrations.RemoveField(
            model_name='thetype',
            name='from_local_api',
        ),
        migrations.AddField(
            model_name='thetype',
            name='osm_type',
            field=models.ManyToManyField(blank=True, to='trash.osmtype'),
        ),
        migrations.AddField(
            model_name='trashtype',
            name='osm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.osmtype'),
        ),
    ]
