# Generated by Django 5.2 on 2026-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_thetype_the_type_es_alter_thetype_the_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetype',
            name='the_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='the_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='the_type_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='the_type_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
