# Generated by Django 5.2 on 2026-06-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_alter_thetype_the_type_alter_thetype_the_type_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashspecificities',
            name='recording_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trashspecificities',
            name='same_session',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trashspecificities',
            name='to_validate',
            field=models.BooleanField(default=False),
        ),
    ]
