# Generated by Django 4.2.15 on 2024-10-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_osmtype_remove_thetype_foreign_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trashtype',
            name='osm_type',
        ),
        migrations.RemoveField(
            model_name='thetype',
            name='osm_type',
        ),
        migrations.DeleteModel(
            name='OSMType',
        ),
        migrations.AddField(
            model_name='thetype',
            name='type_locale',
            field=models.ManyToManyField(blank=True, to='trash.typelocale'),
        ),
        migrations.AddField(
            model_name='thetype',
            name='osm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_local', to='trash.thetype'),
        ),
    ]
