# Generated by Django 4.2.15 on 2024-10-22 15:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_typelocale_remove_trashtype_osm_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typelocale',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='thetype',
            name='type_locale',
        ),
        migrations.AddField(
            model_name='typelocale',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typelocale',
            name='the_type',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_the_type', to='trash.thetype'),
        ),
    ]
