# Generated by Django 4.2.15 on 2024-11-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0005_alter_typelocale_options_remove_thetype_type_locale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashspecificities',
            name='trash_type',
        ),
        migrations.AddField(
            model_name='trashspecificities',
            name='trash_type',
            field=models.ManyToManyField(blank=True, to='trash.trashtype'),
        ),
    ]
