# Generated by Django 4.2.15 on 2024-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0006_remove_trashspecificities_trash_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetype',
            name='icon',
            field=models.CharField(blank=True, choices=[('Cardboard', 'cardboard'), ('Glass', 'glass-bottle'), ('Can', 'can'), ('Paper', 'paper'), ('Plastic', 'plastic-bottle'), ('Recycling material', 'recycle'), ('Special waste', 'special-bin'), ('General trash', 'trash-icon')], max_length=23, null=True),
        ),
    ]
