# Generated by Django 4.2.15 on 2024-12-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0007_thetype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetype',
            name='icon',
            field=models.CharField(blank=True, choices=[('cardboard', 'Cardboard'), ('glass-bottle', 'Glass'), ('can', 'Can'), ('paper', 'Paper'), ('plastic-bottle', 'Plastic'), ('recycle', 'Recycling material'), ('special-bin', 'Special waste'), ('trash-icon', 'General trash')], max_length=23, null=True),
        ),
        migrations.RemoveField(
            model_name='thetype',
            name='osm_type',
        ),
        migrations.AddField(
            model_name='thetype',
            name='osm_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_osm', to='trash.thetype'),
        ),
    ]
