# Generated by Django 4.2.15 on 2024-12-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0008_alter_thetype_icon_remove_thetype_osm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetype',
            name='is_osm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='osm_type',
            field=models.ManyToManyField(blank=True, to='trash.thetype'),
        ),
    ]
