# Generated by Django 4.2.15 on 2025-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0019_registerapi_register_file_alter_registerapi_api_type'),
        ('trash', '0009_thetype_is_osm_alter_thetype_osm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashspecificities',
            name='osm_trash_spec',
            field=models.ManyToManyField(blank=True, related_name='osm_trash_spec', to='datapop.pointfield'),
        ),
        migrations.AlterField(
            model_name='thetype',
            name='icon',
            field=models.CharField(choices=[('cardboard', 'Cardboard'), ('glass-bottle', 'Glass'), ('can', 'Can'), ('paper', 'Paper'), ('plastic-bottle', 'Plastic'), ('recycle', 'Recycling material'), ('special-bin', 'Special waste'), ('trash-icon', 'General trash'), ('shirt', 'Clothes')], default='trash-icon', max_length=23),
        ),
    ]
