# Generated by Django 4.2.15 on 2025-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0010_trashspecificities_osm_trash_spec_alter_thetype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectarea',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
