# Generated by Django 4.2.15 on 2025-04-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0021_remove_registerapichosen_ticked_and_more'),
        ('trash', '0011_collectarea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectarea',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.textfield'),
        ),
    ]
