# Generated by Django 4.2.20 on 2025-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0012_alter_collectarea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetype',
            name='icon',
            field=models.CharField(choices=[('cardboard', 'Cardboard'), ('glassbottle', 'Glass'), ('can', 'Can'), ('paper', 'Paper'), ('plasticbottle', 'Plastic'), ('recycle', 'Recycling material'), ('specialbin', 'Special waste'), ('trashicon', 'General trash'), ('shirt', 'Clothes')], default='trashicon', max_length=23),
        ),
    ]
