# Generated by Django 4.2.28 on 2026-02-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0013_alter_thetype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='the_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.thetype'),
        ),
    ]
