# Generated by Django 5.2 on 2026-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0015_alter_collectarea_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectarea',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
