# Generated by Django 5.2 on 2026-03-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0027_alter_registerapichosen_register_api'),
        ('trash', '0016_alter_collectarea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectarea',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_description', to='datapop.textfield'),
        ),
    ]
