# Generated by Django 4.2.15 on 2024-08-15 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_chosen', models.CharField(blank=True, max_length=250, null=True)),
                ('value_example', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.PositiveIntegerField(blank=True, null=True)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('the_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(blank=True, choices=[('Booleanfield', 'BooleanField'), ('Charfield', 'CharField'), ('Datefield', 'DateField'), ('Datetimefield', 'DateTimeField'), ('Emailfield', 'EmailField'), ('Filepathfield', 'FilePathField'), ('Floatfield', 'FloatField'), ('Integerfield', 'IntegerField'), ('Positiveintegerfield', 'PositiveIntegerField'), ('Textfield', 'TextField'), ('Timefield', 'TimeField'), ('Urlfield', 'URLField'), ('Filefield', 'FileField'), ('Imagefield', 'ImageField'), ('Jsonfield', 'JSONField'), ('Geometrycollectionfield', 'GeometryCollectionField'), ('Geometryfield', 'GeometryField'), ('Linestringfield', 'LinestringField'), ('MultilineStringfield', 'MultiLineStringField'), ('Multipointfield', 'MultiPointField'), ('Multipolygonfield', 'MultiPolygonField'), ('Pointfield', 'PointField'), ('Polygonfield', 'PolygonField')], max_length=23, null=True)),
                ('field_name', models.CharField(blank=True, max_length=250, null=True)),
                ('operation', models.CharField(blank=True, choices=[('COMBINE', 'COMBINE'), ('ADD', 'ADD'), ('SUBSTRAC', 'SUBSTRACT'), ('DIVIDE', 'DIVIDE'), ('MULTIPLY', 'MULTIPLY'), ('PERCENTAGE', 'PERCENTAGE')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterAPI',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('api_title', models.TextField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('api_endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('api_type', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('OSM', 'OSM'), ('OTHER', 'OTHER')], max_length=10, null=True)),
                ('is_dumb', models.BooleanField(default=False)),
                ('first', models.BooleanField(default=True)),
                ('the_time', models.DateTimeField(auto_now=True)),
                ('pagination', models.CharField(max_length=100)),
                ('pagination_number', models.PositiveIntegerField(default=0)),
                ('rows_name', models.CharField(max_length=100)),
                ('rows_per_page', models.PositiveIntegerField()),
                ('once_every', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep', models.PositiveIntegerField(blank=True, null=True)),
                ('json_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('results', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterAPIChosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('hierarchy', models.PositiveIntegerField(blank=True, null=True)),
                ('ticked', models.BooleanField(default=False)),
                ('is_list', models.BooleanField(default=False)),
                ('field_type', models.CharField(blank=True, choices=[('Booleanfield', 'BooleanField'), ('Charfield', 'CharField'), ('Datefield', 'DateField'), ('Datetimefield', 'DateTimeField'), ('Emailfield', 'EmailField'), ('Filepathfield', 'FilePathField'), ('Floatfield', 'FloatField'), ('Integerfield', 'IntegerField'), ('Positiveintegerfield', 'PositiveIntegerField'), ('Textfield', 'TextField'), ('Timefield', 'TimeField'), ('Urlfield', 'URLField'), ('Filefield', 'FileField'), ('Imagefield', 'ImageField'), ('Jsonfield', 'JSONField'), ('Geometrycollectionfield', 'GeometryCollectionField'), ('Geometryfield', 'GeometryField'), ('Linestringfield', 'LinestringField'), ('Multilinestringfield', 'MultiLineStringField'), ('Multipointfield', 'MultiPointField'), ('Multipolygonfield', 'MultiPolygonField'), ('Pointfield', 'PointField'), ('Polygonfield', 'PolygonField')], max_length=23, null=True)),
                ('field_name', models.CharField(blank=True, max_length=250, null=True)),
                ('children_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
                ('chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='datapop.chosen')),
                ('line_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_id', to='datapop.registerapichosen')),
                ('register_api', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_api', to='datapop.registerapi')),
                ('register_api_foreign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.registerapi')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urlfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.URLField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Timefield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.TimeField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Textfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.TextField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Positiveintegerfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.PositiveIntegerField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Polygonfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Pointfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.AddField(
            model_name='operatedfield',
            name='register_api_chosen',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='datapop.registerapichosen'),
        ),
        migrations.CreateModel(
            name='Multipolygonfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Multipointfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Multilinestringfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.CharField(max_length=50)),
                ('features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.locationfeature')),
            ],
        ),
        migrations.CreateModel(
            name='Linestringfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Jsonfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.JSONField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Integerfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.IntegerField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Imagefield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Geometryfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Geometrycollectionfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Floatfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.FloatField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Filepathfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.FilePathField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Filefield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.FileField(blank=True, null=True, upload_to='')),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Emailfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Datetimefield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.DateTimeField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Datefield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.DateField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.AddField(
            model_name='dataline',
            name='register_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.registerapi'),
        ),
        migrations.AddField(
            model_name='dataline',
            name='register_api_chosen',
            field=models.ManyToManyField(blank=True, to='datapop.registerapichosen'),
        ),
        migrations.CreateModel(
            name='Charfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.CharField(blank=True, max_length=250, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
        migrations.CreateModel(
            name='Booleanfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('o_field', models.BooleanField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('data_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.dataline')),
                ('operated_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.operatedfield')),
                ('register_api_chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapichosen')),
            ],
        ),
    ]
