# Generated by Django 4.2.15 on 2024-08-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='charfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='datefield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='datetimefield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='emailfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='filefield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='filepathfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='floatfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='geometrycollectionfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='geometryfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='imagefield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='jsonfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='linestringfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='multilinestringfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='multipointfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='multipolygonfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='pointfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='polygonfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='positiveintegerfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='timefield',
            name='data_line',
        ),
        migrations.RemoveField(
            model_name='urlfield',
            name='data_line',
        ),
        migrations.AddField(
            model_name='booleanfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='charfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='datetimefield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='emailfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='filefield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='filepathfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='floatfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='geometrycollectionfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='geometryfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='imagefield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='jsonfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='linestringfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='multilinestringfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='multipointfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='multipolygonfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='pointfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='polygonfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='positiveintegerfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='timefield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
        migrations.AddField(
            model_name='urlfield',
            name='data_line',
            field=models.ManyToManyField(blank=True, null=True, to='datapop.dataline'),
        ),
    ]
