# Generated by Django 4.2.15 on 2024-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0003_alter_booleanfield_data_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='where_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
