# Generated by Django 4.2.15 on 2024-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0004_registerapi_where_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapi',
            name='where_line',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
