# Generated by Django 4.2.15 on 2024-09-03 13:25

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0006_alter_registerapi_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='register_api_foreign',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_api', to='datapop.registerapi'),
        ),
    ]
