# Generated by Django 4.2.15 on 2024-09-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0007_alter_registerapichosen_register_api_foreign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='register_api_foreign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_api', to='datapop.registerapi'),
        ),
    ]
