# Generated by Django 4.2.15 on 2024-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0008_alter_registerapichosen_register_api_foreign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapi',
            name='pagination_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
