# Generated by Django 4.2.15 on 2024-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0009_alter_registerapi_pagination_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='until_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
