# Generated by Django 4.2.15 on 2024-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0010_registerapi_until_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapi',
            name='api_type',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('CSV', 'CSV'), ('OSM', 'OSM'), ('OTHER', 'OTHER')], max_length=10, null=True),
        ),
    ]
