# Generated by Django 4.2.15 on 2024-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0011_alter_registerapi_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
