# Generated by Django 4.2.15 on 2024-09-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0012_alter_registerapichosen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='register_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_api', to='datapop.registerapi'),
        ),
    ]
