# Generated by Django 4.2.15 on 2024-09-23 08:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0013_alter_registerapichosen_register_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='register_api',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_api', to='datapop.registerapi'),
        ),
    ]
