# Generated by Django 4.2.15 on 2024-09-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0014_alter_registerapichosen_register_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerapichosen',
            name='chosen',
        ),
        migrations.AddField(
            model_name='registerapichosen',
            name='the_chosen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapop.chosen'),
        ),
    ]
