# Generated by Django 4.2.15 on 2024-09-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0015_remove_registerapichosen_chosen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='the_chosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_chosen', to='datapop.chosen'),
        ),
    ]
