# Generated by Django 4.2.15 on 2024-09-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0016_alter_registerapichosen_the_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='the_chosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosing', to='datapop.chosen'),
        ),
    ]
