# Generated by Django 4.2.15 on 2024-10-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0017_alter_registerapichosen_the_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
