# Generated by Django 4.2.15 on 2025-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0018_registerapi_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='register_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='registerapi',
            name='api_type',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('KML', 'KML'), ('OSM', 'OSM'), ('OTHER', 'OTHER')], max_length=10, null=True),
        ),
    ]
