# Generated by Django 4.2.15 on 2025-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0019_registerapi_register_file_alter_registerapi_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapi',
            name='register_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
