# Generated by Django 4.2.15 on 2025-03-18 09:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0020_alter_registerapi_register_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerapichosen',
            name='ticked',
        ),
        migrations.AddField(
            model_name='registerapi',
            name='api_trash',
            field=models.CharField(blank=True, choices=[('TRASHSPECIFICITIES', 'TRASHSPECIFICITIES'), ('COLLECTAREA', 'COLLECTAREA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerapichosen',
            name='json_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registerapi',
            name='register_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/racine/development/trashit/trashit/private'), upload_to=''),
        ),
    ]
