# Generated by Django 4.2.20 on 2025-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0021_remove_registerapichosen_ticked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
