# Generated by Django 4.2.20 on 2025-05-12 13:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0022_registerapi_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLocalWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('register_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapop.registerapi')),
            ],
        ),
    ]
