# Generated by Django 4.2.20 on 2025-05-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0023_requestlocalwaste'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlocalwaste',
            name='allow_requested',
            field=models.BooleanField(default=False),
        ),
    ]
