# Generated by Django 4.2.28 on 2026-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0024_requestlocalwaste_allow_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='api_trash_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
