# Generated by Django 4.2.28 on 2026-02-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0025_registerapi_api_trash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='register_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_api', to='datapop.registerapi'),
        ),
    ]
