# Generated by Django 4.2.28 on 2026-02-26 14:11

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0026_alter_registerapichosen_register_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapichosen',
            name='register_api',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_api', to='datapop.registerapi'),
        ),
    ]
