# Generated by Django 5.2 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapop', '0027_alter_registerapichosen_register_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapi',
            name='admin_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
